# ─── MangoHud — Legacy Gaming Overlay ─────────────────

fps
frametime
frame_timing = 0
fps_limit = 0
vsync = 0

gpu_stats
gpu_temp
cpu_stats
cpu_temp
ram

position = top-right
width = 260
height = 0

font_size = 20
font_file = /usr/share/fonts/TTF/JetBrainsMono-Regular.ttf

background_alpha = 0.6
background_color = 282828

text_color = ebdbb2
gpu_color  = 83a598
cpu_color  = fabd2f
fps_color_change = 1
fps_value = 60,90
fps_color = fb4934,d79921,b8bb26

round_corners = 8
no_display = 0

output_file = /tmp/mangohud_fps.log
log_interval = 500
